<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#Clean-data-with-Python-Pandas" data-toc-modified-id="Clean-data-with-Python-Pandas-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Clean data with Python Pandas</a></span><ul class="toc-item"><li><span><a href="#About-Jupyter-Notebooks-and-Pandas" data-toc-modified-id="About-Jupyter-Notebooks-and-Pandas-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>About Jupyter Notebooks and Pandas</a></span></li></ul></li><li><span><a href="#Getting-started" data-toc-modified-id="Getting-started-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Getting started</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Import-data" data-toc-modified-id="Import-data-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>Import data</a></span></li></ul></li><li><span><a href="#Explore-data" data-toc-modified-id="Explore-data-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Explore data</a></span></li></ul></li><li><span><a href="#Clean-data" data-toc-modified-id="Clean-data-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Clean data</a></span><ul class="toc-item"><li><span><a href="#Cleaning-strings" data-toc-modified-id="Cleaning-strings-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Cleaning strings</a></span></li><li><span><a href="#Delete-columns" data-toc-modified-id="Delete-columns-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Delete columns</a></span></li><li><span><a href="#Renaming-columns" data-toc-modified-id="Renaming-columns-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Renaming columns</a></span></li><li><span><a href="#Clean-up-column-names" data-toc-modified-id="Clean-up-column-names-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Clean up column names</a></span></li><li><span><a href="#Cleaning-dates" data-toc-modified-id="Cleaning-dates-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Cleaning dates</a></span></li><li><span><a href="#Adding-columns-with-year-and-month" data-toc-modified-id="Adding-columns-with-year-and-month-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Adding columns with year and month</a></span></li></ul></li><li><span><a href="#Removing-columns" data-toc-modified-id="Removing-columns-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Removing columns</a></span><ul class="toc-item"><li><span><a href="#Save-your-data" data-toc-modified-id="Save-your-data-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Save your data</a></span></li></ul></li></ul></div>

  # Clean data with Python Pandas

Welcome to this Jupyter Notebook! 
  
Today you'll learn how to import a CSV file into a Jupyter Notebook, and how to clean up messy data. This notebook is part of the course Python for Journalists at [Learno.net](learno.net). The data used originally comes from [the Electoral Commission website](http://search.electoralcommission.org.uk/Search?currentPage=1&rows=10&sort=AcceptedDate&order=desc&tab=1&open=filter&et=pp&isIrishSourceYes=false&isIrishSourceNo=false&date=Reported&from=&to=&quarters=2018Q12&rptPd=3617&prePoll=false&postPoll=false&donorStatus=individual&donorStatus=tradeunion&donorStatus=company&donorStatus=unincorporatedassociation&donorStatus=publicfund&donorStatus=other&donorStatus=registeredpoliticalparty&donorStatus=friendlysociety&donorStatus=trust&donorStatus=limitedliabilitypartnership&donorStatus=impermissibledonor&donorStatus=na&donorStatus=unidentifiabledonor&donorStatus=buildingsociety&register=ni&register=gb&optCols=Register&optCols=IsIrishSource&optCols=ReportingPeriodName), but is edited for training purposes. The edited dataset is available on the Learno website. 

Remember: before you start working with data, make sure to create a copy of the original dataset.

## About Jupyter Notebooks and Pandas

Right now you're looking at a Jupyter Notebook: an interactive, browser based programming environment. You can use these notebooks to program in R, Julia or Python - as you'll be doing later on. Read more about Jupyter Notebook in the [Jupyter Notebook Quick Start Guide](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/what_is_jupyter.html). 
  
To clean up our data, we'll be using Python and Pandas. Pandas is an open-source Python library - basically an extra toolkit to go with Python - that is designed for data analysis. Pandas is flexible, easy to use and has lots of useful functions built right in. Read more about Pandas and its features in [the Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).

**Notebook shortcuts**  

Within Jupyter Notebooks, there are some shortcuts you can use. If you'll be using more notebooks for your data analysis in the future, you'll remember these shortcuts soon enough. :) 

* `esc` will take you into command mode
* `a` will insert cell above
* `b` will insert cell below
* `shift then tab` will show you the documentation for your code
* `shift and enter` will run your cell
* ` d d` will delete a cell

**Pandas dictionary**

* **dataframe**: dataframe is Pandas speak for a table with a labeled y-axis, also known as an index. (The index usually starts at 0.)
* **series**: a series is a list, a series can be made of a single column within a dataframe.

Before we dive in, a little more about Jupyter Notebooks. Every notebooks is made out of cells. A cell can either contain Markdown text - like this one - or code. In the latter you can execute your code. To see what that means, type the following command in the next cell `print("hello world")`.

In [28]:
print('hello world')

hello world

OK, if you're good to go, let dive in...

# Getting started

Before we can work on our data, we need to import all libraries we'll need. In this case, we need to import the Pandas library. You can do that by typing in `import pandas as pd`.

In [30]:
import pandas as pd

`as pd` means that when you'll be writing code you can refer to the library by writing `pd` instead of `pandas`. It's just a little bit shorter and therefore more efficient - something programmers like a lot.

### Import data

For this course, we'll be using data on donations done to British political parties. The data was originally downloaded from [the Electoral Commission website](http://search.electoralcommission.org.uk/Search?currentPage=1&rows=10&sort=AcceptedDate&order=desc&tab=1&open=filter&et=pp&isIrishSourceYes=false&isIrishSourceNo=false&date=Reported&from=&to=&quarters=2018Q12&rptPd=3617&prePoll=false&postPoll=false&donorStatus=individual&donorStatus=tradeunion&donorStatus=company&donorStatus=unincorporatedassociation&donorStatus=publicfund&donorStatus=other&donorStatus=registeredpoliticalparty&donorStatus=friendlysociety&donorStatus=trust&donorStatus=limitedliabilitypartnership&donorStatus=impermissibledonor&donorStatus=na&donorStatus=unidentifiabledonor&donorStatus=buildingsociety&register=ni&register=gb&optCols=Register&optCols=IsIrishSource&optCols=ReportingPeriodName).

We are going to create a dataframe by importing a CSV with our data. Data can be imported using the following code: `df = pd.read_csv('filename.csv')`.

In [41]:
pd.read_csv('results.csv')

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,IsReportedPrePoll,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource
0,C0363977,Plaid Cymru - The Party of Wales,Political Party,"£20,000.00",19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,...,NaN,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False
1,C0364233,Liberal Democrats,Political Party,"£1,800.00",31/12/2017,Greater Reading,Ms Kirsten Bayes,False,False,Individual,...,NaN,Q4 2017,False,True,90,1998.0,43033,NaN,Great Britain,False
2,C0364187,Liberal Democrats,Political Party,"£3,000.00",31/12/2017,South Gloucestershire,Mr Steve Webb,False,False,Individual,...,NaN,Q4 2017,False,True,90,5141.0,35400,NaN,Great Britain,False
3,C0364207,Liberal Democrats,Political Party,"£1,560.00",31/12/2017,Westmorland and Lonsdale,Mr Tim Farron,False,False,Individual,...,NaN,Q4 2017,False,True,90,2386.0,76661,NaN,Great Britain,False
4,C0364113,Liberal Democrats,Political Party,"£7,750.00",31/12/2017,Central Party,Mr Duncan Greenland,True,False,Individual,...,NaN,Q4 2017,False,True,90,NaN,35403,NaN,Great Britain,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,C0363988,UK Independence Party (UKIP),Political Party,"£1,000.00",26/01/2017,Central Party,Mr Duncan Greenland,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,83323,NaN,Great Britain,False
296,C0364018,UK Independence Party (UKIP),Political Party,"£5,000.00",26/01/2017,Central Party,Lord D Stevens of Ludgate,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,48879,NaN,Great Britain,False
297,C0364007,UK Independence Party (UKIP),Political Party,"£1,000.00",13/01/2017,Central Party,Mr Duncan Greenland,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,74686,NaN,Great Britain,False
298,C0363987,UK Independence Party (UKIP),Political Party,"£1,000.00",12/01/2017,Central Party,Mr Malcolm Bluemel,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,83323,NaN,Great Britain,False
299,C0393892,Labour Party,Political Party,"£1,000.00",10/01/2017,Folkestone and Hythe CLP,Mr Duncan Greenland,True,False,Individual,...,NaN,Q4 2017,False,True,53,295.0,83996,NaN,Great Britain,False

Sometimes you'll have a CSV file that doesn't use comma's to seperate values, but uses semi-colons or something else entirely. To import such a dataset change the code into:  
`df = pd.read_csv('filename.csv', delimiter=";")`.

## Explore data

When importing our data, we save the CSV file inside a dataframe that is called `df`. We can now explore the data by refering to the dataframe as `df`. It's important to 'get to know' your data, so you know what you're working with.

Use `df.head(10)` to look at the first ten rows of the data:

In [42]:
df.head(10)

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,IsReportedPrePoll,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource
0,C0363977,Plaid Cymru - The Party of Wales,Political Party,"£20,000.00",19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,...,NaN,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False
1,C0364233,Liberal Democrats,Political Party,"£1,800.00",31/12/2017,Greater Reading,Ms Kirsten Bayes,False,False,Individual,...,NaN,Q4 2017,False,True,90,1998.0,43033,NaN,Great Britain,False
2,C0364187,Liberal Democrats,Political Party,"£3,000.00",31/12/2017,South Gloucestershire,Mr Steve Webb,False,False,Individual,...,NaN,Q4 2017,False,True,90,5141.0,35400,NaN,Great Britain,False
3,C0364207,Liberal Democrats,Political Party,"£1,560.00",31/12/2017,Westmorland and Lonsdale,Mr Tim Farron,False,False,Individual,...,NaN,Q4 2017,False,True,90,2386.0,76661,NaN,Great Britain,False
4,C0364113,Liberal Democrats,Political Party,"£7,750.00",31/12/2017,Central Party,Mr Duncan Greenland,True,False,Individual,...,NaN,Q4 2017,False,True,90,NaN,35403,NaN,Great Britain,False
5,C0364156,Liberal Democrats,Political Party,"£1,800.00",31/12/2017,Hazel Grove,Mr Michael Lees,False,False,Individual,...,NaN,Q4 2017,False,True,90,2022.0,76645,NaN,Great Britain,False
6,C0364219,Liberal Democrats,Political Party,"£1,838.00",31/12/2017,Cheltenham,Ms Jane Mactaggart,False,False,Individual,...,NaN,Q4 2017,False,True,90,1873.0,47793,NaN,Great Britain,False
7,C0364238,Liberal Democrats,Political Party,"£1,779.00",31/12/2017,Gloucester,Mr Jeremy Hilton,False,False,Individual,...,NaN,Q4 2017,False,True,90,1991.0,83347,NaN,Great Britain,False
8,C0364264,Liberal Democrats,Political Party,"£2,400.00",31/12/2017,Parliamentary Party In The Lords,Baroness Kathryn Parminter,False,False,Individual,...,NaN,Q4 2017,False,True,90,4578.0,37433,NaN,Great Britain,False
9,C0364101,Liberal Democrats,Political Party,"£1,560.00",31/12/2017,Yeovil,Lady Catherine Bakewell,False,False,Individual,...,NaN,Q4 2017,False,True,90,2414.0,50620,NaN,Great Britain,False

Use `df.tail(10)` to look at the last ten rows of the data:

In [43]:
df.tail(10)

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,IsReportedPrePoll,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource
290,NC0364001,UK Independence Party (UKIP),Political Party,£650.00,31/03/2017,Harwich and North Essex,Mr Duncan Greenland,False,False,Individual,...,NaN,Q4 2017,False,True,85,4914.0,83324,NaN,Great Britain,False
291,C0376428,Conservative and Unionist Party,Political Party,"£2,500.00",27/03/2017,Havant,Mr Jeremy Hand,False,False,Individual,...,NaN,Q4 2017,False,False,52,1253.0,83880,NaN,Great Britain,False
292,C0363992,UK Independence Party (UKIP),Political Party,"£2,500.00",15/02/2017,Central Party,Professor Tim Congdon,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,38170,NaN,Great Britain,False
293,C0364019,UK Independence Party (UKIP),Political Party,"£1,000.00",08/02/2017,Central Party,Lord D Stevens of Ludgate,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,48879,NaN,Great Britain,False
294,C0363993,UK Independence Party (UKIP),Political Party,"£5,000.00",26/01/2017,Central Party,Professor Tim Congdon,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,38170,NaN,Great Britain,False
295,C0363988,UK Independence Party (UKIP),Political Party,"£1,000.00",26/01/2017,Central Party,Mr Duncan Greenland,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,83323,NaN,Great Britain,False
296,C0364018,UK Independence Party (UKIP),Political Party,"£5,000.00",26/01/2017,Central Party,Lord D Stevens of Ludgate,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,48879,NaN,Great Britain,False
297,C0364007,UK Independence Party (UKIP),Political Party,"£1,000.00",13/01/2017,Central Party,Mr Duncan Greenland,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,74686,NaN,Great Britain,False
298,C0363987,UK Independence Party (UKIP),Political Party,"£1,000.00",12/01/2017,Central Party,Mr Malcolm Bluemel,False,False,Individual,...,NaN,Q4 2017,False,True,85,NaN,83323,NaN,Great Britain,False
299,C0393892,Labour Party,Political Party,"£1,000.00",10/01/2017,Folkestone and Hythe CLP,Mr Duncan Greenland,True,False,Individual,...,NaN,Q4 2017,False,True,53,295.0,83996,NaN,Great Britain,False

To look at a random sample of the data set, typ `df.sample(5)`.

In [44]:
df.sample(10)

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,IsReportedPrePoll,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource
155,C0376309,Conservative and Unionist Party,Political Party,"£12,500.00",07/12/2017,Central Party,Lady Sarah L Keswick,False,False,Individual,...,NaN,Q4 2017,False,False,52,NaN,83840,NaN,Great Britain,False
90,C0364227,Liberal Democrats,Political Party,"£1,720.00",31/12/2017,Sutton,Mrs Marlene Heron,False,False,Individual,...,NaN,Q4 2017,False,True,90,2318.0,54404,NaN,Great Britain,False
86,C0364152,Liberal Democrats,Political Party,"£15,000.00",31/12/2017,Central Party,Mr Mark Petterson,False,False,Individual,...,NaN,Q4 2017,False,False,90,NaN,55995,NaN,Great Britain,False
162,C0376324,Conservative and Unionist Party,Political Party,"£50,000.00",04/12/2017,Central Party,Mr Malcolm Bluemel,False,False,Individual,...,NaN,Q4 2017,False,False,52,NaN,72651,NaN,Great Britain,False
233,C0376394,Conservative and Unionist Party,Political Party,"£2,000.00",25/10/2017,South East Cambridgeshire,Mr Ravi S Kailas,False,False,Individual,...,NaN,Q4 2017,False,False,52,1571.0,74743,NaN,Great Britain,False
175,C0364243,Liberal Democrats,Political Party,"£1,568.08",30/11/2017,Mole Valley,Mrs Hazel Watson,False,False,Individual,...,NaN,Q4 2017,False,False,90,2125.0,83349,NaN,Great Britain,False
137,C0376289,Conservative and Unionist Party,Political Party,"£271,000.00",14/12/2017,Central Party,Mr Michael Davis,False,False,Individual,...,NaN,Q4 2017,False,False,52,NaN,34240,NaN,Great Britain,False
269,C0364133,Liberal Democrats,Political Party,"£23,000.00",30/06/2017,Liberal Democrat Women,Ms Jane Mactaggart,False,False,Individual,...,NaN,Q4 2017,False,False,90,2399.0,55988,NaN,Great Britain,False
190,C0376325,Conservative and Unionist Party,Political Party,"£8,500.00",21/11/2017,Central Party,Ms Nadezda Rodicheva,False,False,Individual,...,NaN,Q4 2017,False,False,52,NaN,81128,NaN,Great Britain,False
107,C0364168,Liberal Democrats,Political Party,"£8,465.00",27/12/2017,Central Party,Mr Peter Wilson,False,False,Individual,...,NaN,Q4 2017,False,True,90,NaN,83334,NaN,Great Britain,False

Next we want to know what data types we're dealing with for each column in our dataframe

Within Python different types of information, have different names. Using `df.dtypes` you can see what data type is in each column of the dataframe. 

**Most common data types**
* **int**: short for integer, a number with no decimal
* **float**: short for floating point, a number with at least one decimal. 
* **string**: usually a bit of text, if there are numbers in a string they are not recognized as such. Python will see a string as text.
* **object**: usually a bit of text, if there are numbers in a string they are not recognized as such. Python will see a string as text.
* **bool**: short for boolean, a binary data type, (true/false)

In [45]:
df.dtypes

ECRef                             object
RegulatedEntityName               object
RegulatedEntityType               object
Value                             object
AcceptedDate                      object
AccountingUnitName                object
DonorName                         object
AccountingUnitsAsCentralParty       bool
IsSponsorship                       bool
DonorStatus                       object
RegulatedDoneeType               float64
CompanyRegistrationNumber        float64
Postcode                         float64
DonationType                      object
NatureOfDonation                  object
PurposeOfVisit                   float64
DonationAction                   float64
ReceivedDate                      object
ReportedDate                      object
IsReportedPrePoll                float64
ReportingPeriodName               object
IsBequest                           bool
IsAggregation                       bool
RegulatedEntityId                  int64
AccountingUnitId                 float64
DonorId                            int64
CampaigningName                  float64
RegisterName                      object
IsIrishSource                       bool
dtype: object

To see the shape of the dataframe - the number of rows and columns - type `df.shape`.

In [46]:
df.shape

(300, 29)

To see a descriptive statistics summary of our data, including the median, average value for every column, type `df.describe()`

In [47]:
df.describe()

,RegulatedDoneeType,CompanyRegistrationNumber,Postcode,PurposeOfVisit,DonationAction,IsReportedPrePoll,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName
count,0.0,0.0,0.0,0.0,0.0,0.0,300.000000,171.000000,300.000000,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,138.116667,2315.818713,65556.336667,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,596.037318,1281.242130,19466.692599,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,52.000000,38.000000,19152.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,52.000000,1512.000000,47058.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,85.000000,2013.000000,76334.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,90.000000,2386.000000,83335.500000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,6595.000000,5278.000000,84031.000000,NaN

As you can see, using `df.describe()`, the Value column is missing. What happened? The most interesting data is in there... Well, remember when we asked Python to give us the data type for each column using `df.dtypes`? 

Turns out, Python doesn't recognize the values in the Value column as numbers. Spoiler alert: that might have something to do with the comma's and pound-sign in that column. Guess what? It's time to do some data cleaning. 

# Clean data

**Clean data to do list**
- make sure that numerical values are recognized as such
- dates are just objects, lets make Python recognize dates as dates
- create new columns based on the date (like a column for year and month)

## Cleaning strings

If we're going to analyse the data, we need the Value column to be recognized as float-numbers. (Floats, not ints since the Value column has numbers with decimals in there.)

First, let's remove all of the pound-signs £... Type `df['ValueClean'] = df['Value'].str.replace('£', '')`. Now, what does this doe? It adds the column ValueClean, which is exactly the same as the column Value, but with every '£' replaced by nothing.

In [48]:
df.sample()

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,IsReportedPrePoll,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource
156,C0376369,Conservative and Unionist Party,Political Party,"£5,000.00",06/12/2017,Hastings & Rye,Mr John D Lovering,False,False,Individual,...,NaN,Q4 2017,False,False,52,1252.0,45696,NaN,Great Britain,False

In [50]:
df['ValueClean'] = df['Value'].str.replace('£', '')

Let's heave a look at the first rows to see how we've done. Remember `df.head()`? ValueClean will be added at the right end of the table...

In [52]:
df.head()

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,ValueClean
0,C0363977,Plaid Cymru - The Party of Wales,Political Party,"£20,000.00",19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,...,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False,20000.00
1,C0364233,Liberal Democrats,Political Party,"£1,800.00",31/12/2017,Greater Reading,Ms Kirsten Bayes,False,False,Individual,...,Q4 2017,False,True,90,1998.0,43033,NaN,Great Britain,False,1800.00
2,C0364187,Liberal Democrats,Political Party,"£3,000.00",31/12/2017,South Gloucestershire,Mr Steve Webb,False,False,Individual,...,Q4 2017,False,True,90,5141.0,35400,NaN,Great Britain,False,3000.00
3,C0364207,Liberal Democrats,Political Party,"£1,560.00",31/12/2017,Westmorland and Lonsdale,Mr Tim Farron,False,False,Individual,...,Q4 2017,False,True,90,2386.0,76661,NaN,Great Britain,False,1560.00
4,C0364113,Liberal Democrats,Political Party,"£7,750.00",31/12/2017,Central Party,Mr Duncan Greenland,True,False,Individual,...,Q4 2017,False,True,90,NaN,35403,NaN,Great Britain,False,7750.00

We're not done yet with this ValueClean column. We need to remove all comma's - Python doesn't like comma's or points for thousands, only for decimals. How would you remove all comma's in the ValueClean column without creating a new column? 
.  
.  
.  
.  
.  
.  
.  
.  
.  
.  
.  
.  
  
The answer looks a lot like `df['ValueClean'] = df['Value'].str.replace('£', '')` but isn't exactly the same...
.  
.  
.  
.  
.  
.  
.  
.  
.  
.  
.  
.  
  
Type `df['ValueClean'] = df['ValueClean'].str.replace(',', '')`, which will replace the column ValueClean with the column ValueClean where all comma's are replaced by nothing.

In [53]:
df['ValueClean'] = df['ValueClean'].str.replace(',', '')

In [54]:
df.sample()

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,ValueClean
29,C0364198,Liberal Democrats,Political Party,"£2,000.00",31/12/2017,Gwynedd and Anglesey,Mr Richard Keatinge,False,False,Individual,...,Q4 2017,False,True,90,2002.0,83335,NaN,Great Britain,False,2000.00

Now, let's see if this did the trick. Use `df.dtypes` to see if the ValueClean column is now a float datatype...

In [55]:
df.dtypes

ECRef                             object
RegulatedEntityName               object
RegulatedEntityType               object
Value                             object
AcceptedDate                      object
AccountingUnitName                object
DonorName                         object
AccountingUnitsAsCentralParty       bool
IsSponsorship                       bool
DonorStatus                       object
RegulatedDoneeType               float64
CompanyRegistrationNumber        float64
Postcode                         float64
DonationType                      object
NatureOfDonation                  object
PurposeOfVisit                   float64
DonationAction                   float64
ReceivedDate                      object
ReportedDate                      object
IsReportedPrePoll                float64
ReportingPeriodName               object
IsBequest                           bool
IsAggregation                       bool
RegulatedEntityId                  int64
AccountingUnitId                 float64
DonorId                            int64
CampaigningName                  float64
RegisterName                      object
IsIrishSource                       bool
ValueClean                        object
dtype: object

Didn't work, huh? That's because we need to explicitly tell Python that the ValueClean column contains float numbers. We can use a Pandas function to do this - like all Pandas functions this one too starts with `pd.`: 

`df['ValueClean'] = pd.to_numeric(df['ValueClean'])`

In [ ]:
df['ValueClean'] = pd.to_numeric(df['ValueClean'])

In [56]:
df.dtypes

ECRef                             object
RegulatedEntityName               object
RegulatedEntityType               object
Value                             object
AcceptedDate                      object
AccountingUnitName                object
DonorName                         object
AccountingUnitsAsCentralParty       bool
IsSponsorship                       bool
DonorStatus                       object
RegulatedDoneeType               float64
CompanyRegistrationNumber        float64
Postcode                         float64
DonationType                      object
NatureOfDonation                  object
PurposeOfVisit                   float64
DonationAction                   float64
ReceivedDate                      object
ReportedDate                      object
IsReportedPrePoll                float64
ReportingPeriodName               object
IsBequest                           bool
IsAggregation                       bool
RegulatedEntityId                  int64
AccountingUnitId                 float64
DonorId                            int64
CampaigningName                  float64
RegisterName                      object
IsIrishSource                       bool
ValueClean                        object
dtype: object

## Delete columns

Ok, now we got our Value column cleaned up in ValueClean; we actually no longer need to keep the original Value column. In Pandas removing or deleting a column is called 'dropping a column'. 

Also good to know: in Pandas, rows (horizontal) in a dataframe have axis=0, columns (vertical) have the first axis (axis=1). 

Knowing this, typing `df = df.drop('Value', 1)` should make sense. It means: the dataframe is the dataframe with the column Value dropped.

In [57]:
df = df.drop('Value', 1)

In [58]:
df.sample()

,ECRef,RegulatedEntityName,RegulatedEntityType,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,RegulatedDoneeType,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,ValueClean
9,C0364101,Liberal Democrats,Political Party,31/12/2017,Yeovil,Lady Catherine Bakewell,False,False,Individual,NaN,...,Q4 2017,False,True,90,2414.0,50620,NaN,Great Britain,False,1560.00

## Renaming columns

With the Value column gone, we can rename ValueClean to Value. Use the following command to do this: `df = df.rename(columns={'old_name': 'new_name'})`

In [61]:
df = df.rename(columns={'ValueClean': 'value'})
df.sample()

,ECRef,RegulatedEntityName,RegulatedEntityType,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,RegulatedDoneeType,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,value
53,C0364224,Liberal Democrats,Political Party,31/12/2017,Merton Borough,Mrs Mary-Jane Jeanes,False,False,Individual,NaN,...,Q4 2017,False,True,90,2109.0,76643,NaN,Great Britain,False,1700.00

## Clean up column names

Since leading and trail spaces will always come back to haunt you in your data analysis nightmares, you want to make sure you get them out of your way before analysing your data. 

Let's see if there are any of these spaces in our column names, by typing `df.columns`, which will give us a list of all column names.

In [62]:
df.columns

Index(['ECRef', 'RegulatedEntityName', 'RegulatedEntityType', 'AcceptedDate',
       'AccountingUnitName', 'DonorName', 'AccountingUnitsAsCentralParty',
       'IsSponsorship', 'DonorStatus', 'RegulatedDoneeType',
       'CompanyRegistrationNumber', 'Postcode', 'DonationType',
       'NatureOfDonation', 'PurposeOfVisit', 'DonationAction', 'ReceivedDate',
       'ReportedDate', 'IsReportedPrePoll', 'ReportingPeriodName', 'IsBequest',
       'IsAggregation', 'RegulatedEntityId', 'AccountingUnitId', 'DonorId',
       'CampaigningName', 'RegisterName', 'IsIrishSource', 'value'],
      dtype='object')

Looking good to me... Let's check all donor names. Get a list of all donor names by using the following command: `df['columnname'].unique()`.

In [64]:
df['DonorName'].unique()

array(['Mr Alun Ffred Jones  ', 'Ms Kirsten Bayes', 'Mr Steve  Webb',
       'Mr Tim Farron', 'Mr Duncan Greenland', 'Mr Michael Lees',
       'Ms Jane Mactaggart', 'Mr Jeremy Hilton',
       'Baroness Kathryn Parminter', 'Lady Catherine Bakewell',
       'Mr Martin Elengorn', 'Cllr Ian Shires', 'Ms Liz  Morris',
       'Dr Alun  Griffiths', 'Mr Dave  Hodgson', 'Mr David Goodwin',
       'Mrs Elizabeth Barraclough', 'Baroness Shirley Williams',
       'Lord Tim Clement-Jones', 'Mr Mark  Burch', 'Mr Arthur Hookway',
       'Mr Brett Hammond', 'Mr Ashley Wood', 'Mrs Rowena Hay',
       'Ms Lynne Featherstone', 'Ms Inga Lockington', 'Mr Peter Rothery',
       'Mr Richard Keatinge', 'Mr Cliff Woodcraft', 'Mr Derek Eastman',
       'Ms Gail  Engert', 'Mr Pathumal Ali', 'Mrs Klara Sudbury',
       'Mr James Macpherson', 'Mr David Tutt', 'Mr Colin  Stears',
       'Ms Mary Wane', 'Mr Alistair  Barr', 'Miss Jocelyn Clark',
       ' Roger Michael Isherwood', 'Mr David E D Brownlow',
       'Mr David E Brownlow', 'Cllr Joe Harris', 'Mr James Baker',
       'Mr Dennis Meredith', 'Ms Anne  Winstanley', 'Mr David Brown',
       'Mr Bernard Fisher', 'Mr A Serge Lourie',
       'Mr Richard Christopher Breen', 'Mr Simon Wheeler',
       'Mrs Mary-Jane Jeanes', 'Lord Richard Allan Of Hallam',
       'Dr Robert Barr', 'Mrs Marian Radford', 'Baroness Barbara Janke',
       'Mr M Joe Boyle', 'Mr Dominic Hiscock',
       'Mr Manuel Abellan-San Martin', 'Ms Helen Clucas',
       'Mr Edward Acland', 'Ms Joanna  Kenny', 'Mr Michael Carter',
       'Ms Ruth  Dombey', 'Ms Karin Snowden', 'Mrs Sunita Gordon',
       'Mr John Hale', 'Lord Paul  Strasburger', 'Mrs Carolyn Lambert',
       'Mr Mark Watkin', 'Mr Andrew  Waller', 'Mr David  Beacham',
       ' Christopher Williams', 'Mr John Mason', 'Mr Steven Lambert',
       'Mrs Isobel McCall', 'Mr Michael Headley', 'Mr Robert Wood',
       'Mr Mark  Petterson', 'Lord Nigel D Jones of Cheltenham',
       'Mr Ian Cuthbertson', 'Mrs Marlene Heron', 'Mr Owen  Temple',
       'Mr Edward Joyce', 'Mr SImon  Curtis', 'Mr Andrew Mckinlay',
       'Ms Philippa  Connor', 'Mrs Hilary Stephenson', 'Mr Chris White',
       'Mr Tom  Gosling', 'Mr Alan  Sherwell',
       'Mr Gerald  Vernon-Jackson', 'Mr Keith Crout',
       'Mr Alexey  Chudnovskiy', ' Stella Creasy', ' Mike Penning',
       'Mr Anthony H Billingham', 'Mr Peter Wilson', 'Mrs Susan  Howes',
       'Mr Greg  Dyke', 'Mr John B Rutter', 'Ms Christine E Dawood',
       'Mr Alan  T Wicnh', 'Mr Stephen Kinsella', 'Mr David W Gray',
       'Mr Robert Chicken', 'Mr Simon D Hume-Kendall',
       'Ms Jennifer  Talbot', 'Sir Michael Hintze', 'Mr Jeremy J Lefroy',
       'Mrs Gitte  Dawson', 'Mr Sam Singh', 'Mr Michael C Warshaw',
       'Mr Edmund G Truell', 'Mr Surinderpal Lit', 'Mr Stephen S Less',
       'Mr Stephen Howard', 'Lord Stanley Fink', 'Mr Dominic R Johnson',
       'Mr Daniel P Hearsum', 'Baroness Emma Nicholson',
       'Mr Nicholas Brougham', 'Dr Arujuna Sivananthan', 'Mr Mark J Page',
       'Mr Michael Davis', 'Mr Michael J Wade', 'Mr Roger Manser',
       'Mr Richard J Grimes', 'Mr Palminder Singh',
       'Lord Charles Falconer of Thoroton', 'Professor Tim Congdon',
       'Mr Arthur P Davidson', 'Mr Mohamed Mansour', 'Mr Peter Cruddas',
       'Mr Alan C Bolton', 'Mr Ian McNish', 'Ms Jean Lambert MEP',
       'Mr Ian Pirie', 'Mr Ian H Leslie-Melville', 'Mr Michael Slade',
       'Lady Sarah L Keswick', 'Mr John D Lovering', 'Mr Dinesh Dhamija',
       'Mr Andrew D Williams', 'Ms Alison Frost',
       'Mr Raymond Chamberlain', 'Ms Elizabeth Reason',
       'Mr Malcolm Bluemel', 'Mrs Catherine Pirie', 'Mr Andrew Law',
       'Ms Alison Johnstone', 'Mr Simon M Haslam', 'Mr Patrick Harvie',
       'Mr Ross John Greer', 'Lord John Crawford',
       'Mr Mark Christopher Ruskell', 'Mr Andrew Dearg Wightman',
       'Mr John Bradford Finnie', 'Mr Michael S Thronton OBE',
       'Mr Henry Keswick', 'Mrs Hazel Watson', 'Mr Gerald H Elliot',
       'Lord Paul Tyler', 'Mr Jeremy RS Hunt', 'Mr Edward  John Izzard',
       'Lord D Stevens of Ludgate', 'Mr Michael Watson',
       'Ms Marina Smethhurst', ' Clive Hollick', 'Mr Abdul-Majid Jafar',
       'Mr Andrew  Godson', 'Mr Stephen P J Matthews',
       'Mr Douglas Reynolds', 'Ms Nadezda Rodicheva', 'Ms Rania K Majeed',
       'Mr Alexander Temerko', 'Mr Howard Leigh', 'Mr Thomas E Notman',
       'Mrs Sarah J Pidgley', 'Mr Philip  L Wroughton',
       'Mr Kenneth J French', 'Mr John Noel Penstone', 'Mrs Mary Erbrich',
       'Mr Patrick D Horsfall', 'Mr Anthony  Harris',
       'Mr Zac F Goldsmith', 'Mr Stephen  Dawson', 'Mr Peter Brown',
       'Mr Tony Belton', 'Mr Jonathan Leslie Skeet', ' William  Goodhart',
       'Mr Roger J Kendrick', 'Mr William Haughey', 'Ms Dora Bertolutti',
       'Mr Neville A Baxter', 'Mr Oluwole Kolade', 'Mr Anthony Bunker',
       'Mr Stephen L Massey', 'Hon George T Farmer',
       'Mr Laurence Hollingworth', 'Ms Anna Gallop', 'Mr Vincent Cable',
       'Mr John D Booth', 'Mrs Esme Forbes', 'Mr Iain Aitken',
       'Mr Byron S Huson', 'Mr Navroz D Udwadia', 'Mr James R Lupton',
       'Mr Ravi S Kailas', 'Mr Nicholas Campsie', 'Mr Nicholas N Moore',
       'Mr William H Salomon', 'Mr Ian R Taylor', 'Lord Philip Harris',
       ' Scirard Lancelyn Green', 'Mr Amjad Bseisu', 'Mr Gary Lydiate',
       'Mr Roger G Orf', 'Ms Jane Turnell-Read', 'Ms Lesley Jackson',
       'Mr Andrew Perloff', 'Mr Donald J Lewin', 'Mr Peter Kane',
       'Mr Roger Nagioff', 'Mr Christopher M Higgins',
       'Mr Michael A Dangoor', 'Mr Robert D Calrow', 'Mr Michael Cohen',
       'Mr Arthur J Taylor', 'Mr David Charles Williams',
       'Mr Robert J Madejski', 'Mr Andrew Pinnock',
       'Lord John Lee Of Trafford', 'Ms Rachel H MacLean',
       'Mr Elizabeth A Gooch', 'Mr Albert Mcintosh',
       'Mr Jeremy J Hosking', 'Mr Neil Record', 'Mrs Menju Mehrotra',
       'Mr Ravi Mehrotra', 'Mr Peter D Landale', 'Mr Daniel D Laycock',
       'Mr Edward P Weatherall', "Mr John O'Hara",
       'Mr Terence F Parkinson', 'Lord John Alderdice', 'Mr Jeremy Hand'],
      dtype=object)

Well, well, well, Mr Alun Ffred Jones  !! It going to take multiple steps to fix that: 
1. Let's make sure the DonorName column is a string.   
Use `df['columnname'] = df['columnname'].astype(str)`
2. Strip all strings in the column of leading and trail spaces.  
Use `df['columnname'] = df['columnname'].map(str.strip)`

In [66]:
df['DonorName'] = df['DonorName'].map(str.strip)

Did that work? Let's see. `df['DonorName'].unique()`

In [67]:
df['DonorName'].unique()

array(['Mr Alun Ffred Jones', 'Ms Kirsten Bayes', 'Mr Steve  Webb',
       'Mr Tim Farron', 'Mr Duncan Greenland', 'Mr Michael Lees',
       'Ms Jane Mactaggart', 'Mr Jeremy Hilton',
       'Baroness Kathryn Parminter', 'Lady Catherine Bakewell',
       'Mr Martin Elengorn', 'Cllr Ian Shires', 'Ms Liz  Morris',
       'Dr Alun  Griffiths', 'Mr Dave  Hodgson', 'Mr David Goodwin',
       'Mrs Elizabeth Barraclough', 'Baroness Shirley Williams',
       'Lord Tim Clement-Jones', 'Mr Mark  Burch', 'Mr Arthur Hookway',
       'Mr Brett Hammond', 'Mr Ashley Wood', 'Mrs Rowena Hay',
       'Ms Lynne Featherstone', 'Ms Inga Lockington', 'Mr Peter Rothery',
       'Mr Richard Keatinge', 'Mr Cliff Woodcraft', 'Mr Derek Eastman',
       'Ms Gail  Engert', 'Mr Pathumal Ali', 'Mrs Klara Sudbury',
       'Mr James Macpherson', 'Mr David Tutt', 'Mr Colin  Stears',
       'Ms Mary Wane', 'Mr Alistair  Barr', 'Miss Jocelyn Clark',
       'Roger Michael Isherwood', 'Mr David E D Brownlow',
       'Mr David E Brownlow', 'Cllr Joe Harris', 'Mr James Baker',
       'Mr Dennis Meredith', 'Ms Anne  Winstanley', 'Mr David Brown',
       'Mr Bernard Fisher', 'Mr A Serge Lourie',
       'Mr Richard Christopher Breen', 'Mr Simon Wheeler',
       'Mrs Mary-Jane Jeanes', 'Lord Richard Allan Of Hallam',
       'Dr Robert Barr', 'Mrs Marian Radford', 'Baroness Barbara Janke',
       'Mr M Joe Boyle', 'Mr Dominic Hiscock',
       'Mr Manuel Abellan-San Martin', 'Ms Helen Clucas',
       'Mr Edward Acland', 'Ms Joanna  Kenny', 'Mr Michael Carter',
       'Ms Ruth  Dombey', 'Ms Karin Snowden', 'Mrs Sunita Gordon',
       'Mr John Hale', 'Lord Paul  Strasburger', 'Mrs Carolyn Lambert',
       'Mr Mark Watkin', 'Mr Andrew  Waller', 'Mr David  Beacham',
       'Christopher Williams', 'Mr John Mason', 'Mr Steven Lambert',
       'Mrs Isobel McCall', 'Mr Michael Headley', 'Mr Robert Wood',
       'Mr Mark  Petterson', 'Lord Nigel D Jones of Cheltenham',
       'Mr Ian Cuthbertson', 'Mrs Marlene Heron', 'Mr Owen  Temple',
       'Mr Edward Joyce', 'Mr SImon  Curtis', 'Mr Andrew Mckinlay',
       'Ms Philippa  Connor', 'Mrs Hilary Stephenson', 'Mr Chris White',
       'Mr Tom  Gosling', 'Mr Alan  Sherwell',
       'Mr Gerald  Vernon-Jackson', 'Mr Keith Crout',
       'Mr Alexey  Chudnovskiy', 'Stella Creasy', 'Mike Penning',
       'Mr Anthony H Billingham', 'Mr Peter Wilson', 'Mrs Susan  Howes',
       'Mr Greg  Dyke', 'Mr John B Rutter', 'Ms Christine E Dawood',
       'Mr Alan  T Wicnh', 'Mr Stephen Kinsella', 'Mr David W Gray',
       'Mr Robert Chicken', 'Mr Simon D Hume-Kendall',
       'Ms Jennifer  Talbot', 'Sir Michael Hintze', 'Mr Jeremy J Lefroy',
       'Mrs Gitte  Dawson', 'Mr Sam Singh', 'Mr Michael C Warshaw',
       'Mr Edmund G Truell', 'Mr Surinderpal Lit', 'Mr Stephen S Less',
       'Mr Stephen Howard', 'Lord Stanley Fink', 'Mr Dominic R Johnson',
       'Mr Daniel P Hearsum', 'Baroness Emma Nicholson',
       'Mr Nicholas Brougham', 'Dr Arujuna Sivananthan', 'Mr Mark J Page',
       'Mr Michael Davis', 'Mr Michael J Wade', 'Mr Roger Manser',
       'Mr Richard J Grimes', 'Mr Palminder Singh',
       'Lord Charles Falconer of Thoroton', 'Professor Tim Congdon',
       'Mr Arthur P Davidson', 'Mr Mohamed Mansour', 'Mr Peter Cruddas',
       'Mr Alan C Bolton', 'Mr Ian McNish', 'Ms Jean Lambert MEP',
       'Mr Ian Pirie', 'Mr Ian H Leslie-Melville', 'Mr Michael Slade',
       'Lady Sarah L Keswick', 'Mr John D Lovering', 'Mr Dinesh Dhamija',
       'Mr Andrew D Williams', 'Ms Alison Frost',
       'Mr Raymond Chamberlain', 'Ms Elizabeth Reason',
       'Mr Malcolm Bluemel', 'Mrs Catherine Pirie', 'Mr Andrew Law',
       'Ms Alison Johnstone', 'Mr Simon M Haslam', 'Mr Patrick Harvie',
       'Mr Ross John Greer', 'Lord John Crawford',
       'Mr Mark Christopher Ruskell', 'Mr Andrew Dearg Wightman',
       'Mr John Bradford Finnie', 'Mr Michael S Thronton OBE',
       'Mr Henry Keswick', 'Mrs Hazel Watson', 'Mr Gerald H Elliot',
       'Lord Paul Tyler', 'Mr Jeremy RS Hunt', 'Mr Edward  John Izzard',
       'Lord D Stevens of Ludgate', 'Mr Michael Watson',
       'Ms Marina Smethhurst', 'Clive Hollick', 'Mr Abdul-Majid Jafar',
       'Mr Andrew  Godson', 'Mr Stephen P J Matthews',
       'Mr Douglas Reynolds', 'Ms Nadezda Rodicheva', 'Ms Rania K Majeed',
       'Mr Alexander Temerko', 'Mr Howard Leigh', 'Mr Thomas E Notman',
       'Mrs Sarah J Pidgley', 'Mr Philip  L Wroughton',
       'Mr Kenneth J French', 'Mr John Noel Penstone', 'Mrs Mary Erbrich',
       'Mr Patrick D Horsfall', 'Mr Anthony  Harris',
       'Mr Zac F Goldsmith', 'Mr Stephen  Dawson', 'Mr Peter Brown',
       'Mr Tony Belton', 'Mr Jonathan Leslie Skeet', 'William  Goodhart',
       'Mr Roger J Kendrick', 'Mr William Haughey', 'Ms Dora Bertolutti',
       'Mr Neville A Baxter', 'Mr Oluwole Kolade', 'Mr Anthony Bunker',
       'Mr Stephen L Massey', 'Hon George T Farmer',
       'Mr Laurence Hollingworth', 'Ms Anna Gallop', 'Mr Vincent Cable',
       'Mr John D Booth', 'Mrs Esme Forbes', 'Mr Iain Aitken',
       'Mr Byron S Huson', 'Mr Navroz D Udwadia', 'Mr James R Lupton',
       'Mr Ravi S Kailas', 'Mr Nicholas Campsie', 'Mr Nicholas N Moore',
       'Mr William H Salomon', 'Mr Ian R Taylor', 'Lord Philip Harris',
       'Scirard Lancelyn Green', 'Mr Amjad Bseisu', 'Mr Gary Lydiate',
       'Mr Roger G Orf', 'Ms Jane Turnell-Read', 'Ms Lesley Jackson',
       'Mr Andrew Perloff', 'Mr Donald J Lewin', 'Mr Peter Kane',
       'Mr Roger Nagioff', 'Mr Christopher M Higgins',
       'Mr Michael A Dangoor', 'Mr Robert D Calrow', 'Mr Michael Cohen',
       'Mr Arthur J Taylor', 'Mr David Charles Williams',
       'Mr Robert J Madejski', 'Mr Andrew Pinnock',
       'Lord John Lee Of Trafford', 'Ms Rachel H MacLean',
       'Mr Elizabeth A Gooch', 'Mr Albert Mcintosh',
       'Mr Jeremy J Hosking', 'Mr Neil Record', 'Mrs Menju Mehrotra',
       'Mr Ravi Mehrotra', 'Mr Peter D Landale', 'Mr Daniel D Laycock',
       'Mr Edward P Weatherall', "Mr John O'Hara",
       'Mr Terence F Parkinson', 'Lord John Alderdice', 'Mr Jeremy Hand'],
      dtype=object)

## Cleaning dates

Ok, so now we've only got to clean up our dates. We're going to use another python library: the datetime library contains some neat and handy datetime tools. Just what we need, type: `import datetime`

In [68]:
import datetime

Let's have another look at some of our data before we start working on the date column. Use `df.head()`, `df.tail()` or my personal favorite `df.sample()`.

In [69]:
df.head(5)

,ECRef,RegulatedEntityName,RegulatedEntityType,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,RegulatedDoneeType,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,value
0,C0363977,Plaid Cymru - The Party of Wales,Political Party,19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,NaN,...,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False,20000.00
1,C0364233,Liberal Democrats,Political Party,31/12/2017,Greater Reading,Ms Kirsten Bayes,False,False,Individual,NaN,...,Q4 2017,False,True,90,1998.0,43033,NaN,Great Britain,False,1800.00
2,C0364187,Liberal Democrats,Political Party,31/12/2017,South Gloucestershire,Mr Steve Webb,False,False,Individual,NaN,...,Q4 2017,False,True,90,5141.0,35400,NaN,Great Britain,False,3000.00
3,C0364207,Liberal Democrats,Political Party,31/12/2017,Westmorland and Lonsdale,Mr Tim Farron,False,False,Individual,NaN,...,Q4 2017,False,True,90,2386.0,76661,NaN,Great Britain,False,1560.00
4,C0364113,Liberal Democrats,Political Party,31/12/2017,Central Party,Mr Duncan Greenland,True,False,Individual,NaN,...,Q4 2017,False,True,90,NaN,35403,NaN,Great Britain,False,7750.00

In [70]:
df.dtypes

ECRef                             object
RegulatedEntityName               object
RegulatedEntityType               object
AcceptedDate                      object
AccountingUnitName                object
DonorName                         object
AccountingUnitsAsCentralParty       bool
IsSponsorship                       bool
DonorStatus                       object
RegulatedDoneeType               float64
CompanyRegistrationNumber        float64
Postcode                         float64
DonationType                      object
NatureOfDonation                  object
PurposeOfVisit                   float64
DonationAction                   float64
ReceivedDate                      object
ReportedDate                      object
IsReportedPrePoll                float64
ReportingPeriodName               object
IsBequest                           bool
IsAggregation                       bool
RegulatedEntityId                  int64
AccountingUnitId                 float64
DonorId                            int64
CampaigningName                  float64
RegisterName                      object
IsIrishSource                       bool
value                             object
dtype: object

Our dates are in the AcceptedDate column. Let's make sure these dates are recognized as such. Use `df['AcceptedDate'] = pd.to_datetime(df['AcceptedDate'], format="%d/%m/%Y")` to change the data type from object to date. Use `df.head()`, `df.tail()` or `df.sample()` to see if it worked.

In [71]:
df['AcceptedDate'] = pd.to_datetime(df['AcceptedDate'], format="%d/%m/%Y")

Now, did the data type of the AcceptedDate column change? Use `df.dtypes` to check.

In [72]:
df.dtypes

ECRef                                    object
RegulatedEntityName                      object
RegulatedEntityType                      object
AcceptedDate                     datetime64[ns]
AccountingUnitName                       object
DonorName                                object
AccountingUnitsAsCentralParty              bool
IsSponsorship                              bool
DonorStatus                              object
RegulatedDoneeType                      float64
CompanyRegistrationNumber               float64
Postcode                                float64
DonationType                             object
NatureOfDonation                         object
PurposeOfVisit                          float64
DonationAction                          float64
ReceivedDate                             object
ReportedDate                             object
IsReportedPrePoll                       float64
ReportingPeriodName                      object
IsBequest                                  bool
IsAggregation                              bool
RegulatedEntityId                         int64
AccountingUnitId                        float64
DonorId                                   int64
CampaigningName                         float64
RegisterName                             object
IsIrishSource                              bool
value                                    object
dtype: object

Worked perfectly! :)   

## Adding columns with year and month

Now, let's create two new columns. One with the month and one with the years... Since Python now knows that the AcceptedDate column contains dates, we can use out-of-the-box functions from pandas and the datetime libraries. 

Creating a column with the years based on the AcceptedDate column, becomes as easy as `df['Year'] = pd.DatetimeIndex(df['AcceptedDate']).year`.

In [73]:
df.sample()

,ECRef,RegulatedEntityName,RegulatedEntityType,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,RegulatedDoneeType,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,value
211,C0393879,Labour Party,Political Party,2017-11-13,Central Party,Lord Charles Falconer of Thoroton,True,False,Individual,NaN,...,Q4 2017,False,True,53,NaN,83993,NaN,Great Britain,False,833.00

In [75]:
df['year'] = pd.DatetimeIndex(df['AcceptedDate']).year

Use `df.head()`, `df.tail()` or `df.sample()` to see if it worked. Our new column will be added on the right side of the dataframe.

To add a column with all months is just as easy. `df['Month'] = pd.DatetimeIndex(df['AcceptedDate']).month` will do the trick, it means: in the dataframe called 'df', create a new column called 'Month' and fill it with months, which you should base on the date inside the column AcceptedDate of the dataframe df.

In [77]:
df['Month'] = pd.DatetimeIndex(df['AcceptedDate']).month
df.tail(10)

,ECRef,RegulatedEntityName,RegulatedEntityType,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,RegulatedDoneeType,...,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,value,year,Month
290,NC0364001,UK Independence Party (UKIP),Political Party,2017-03-31,Harwich and North Essex,Mr Duncan Greenland,False,False,Individual,NaN,...,True,85,4914.0,83324,NaN,Great Britain,False,650.00,2017,3
291,C0376428,Conservative and Unionist Party,Political Party,2017-03-27,Havant,Mr Jeremy Hand,False,False,Individual,NaN,...,False,52,1253.0,83880,NaN,Great Britain,False,2500.00,2017,3
292,C0363992,UK Independence Party (UKIP),Political Party,2017-02-15,Central Party,Professor Tim Congdon,False,False,Individual,NaN,...,True,85,NaN,38170,NaN,Great Britain,False,2500.00,2017,2
293,C0364019,UK Independence Party (UKIP),Political Party,2017-02-08,Central Party,Lord D Stevens of Ludgate,False,False,Individual,NaN,...,True,85,NaN,48879,NaN,Great Britain,False,1000.00,2017,2
294,C0363993,UK Independence Party (UKIP),Political Party,2017-01-26,Central Party,Professor Tim Congdon,False,False,Individual,NaN,...,True,85,NaN,38170,NaN,Great Britain,False,5000.00,2017,1
295,C0363988,UK Independence Party (UKIP),Political Party,2017-01-26,Central Party,Mr Duncan Greenland,False,False,Individual,NaN,...,True,85,NaN,83323,NaN,Great Britain,False,1000.00,2017,1
296,C0364018,UK Independence Party (UKIP),Political Party,2017-01-26,Central Party,Lord D Stevens of Ludgate,False,False,Individual,NaN,...,True,85,NaN,48879,NaN,Great Britain,False,5000.00,2017,1
297,C0364007,UK Independence Party (UKIP),Political Party,2017-01-13,Central Party,Mr Duncan Greenland,False,False,Individual,NaN,...,True,85,NaN,74686,NaN,Great Britain,False,1000.00,2017,1
298,C0363987,UK Independence Party (UKIP),Political Party,2017-01-12,Central Party,Mr Malcolm Bluemel,False,False,Individual,NaN,...,True,85,NaN,83323,NaN,Great Britain,False,1000.00,2017,1
299,C0393892,Labour Party,Political Party,2017-01-10,Folkestone and Hythe CLP,Mr Duncan Greenland,True,False,Individual,NaN,...,True,53,295.0,83996,NaN,Great Britain,False,1000.00,2017,1

Use `df.head()`, `df.tail()` or `df.sample()` to see if it worked. For something like this, i like to use the `df.sample()` function; it allows you to see if it worked with different values. 

Off course this new column too is  added on the right side of the dataframe.

# Removing columns

Our dataframe is quite big. Maybe we can remove some columns? Let's see how many columns we got... Use `df.columns` and `df.shape` to familiarize yourself with the number of columns and their names.

In [78]:
df.columns

Index(['ECRef', 'RegulatedEntityName', 'RegulatedEntityType', 'AcceptedDate',
       'AccountingUnitName', 'DonorName', 'AccountingUnitsAsCentralParty',
       'IsSponsorship', 'DonorStatus', 'RegulatedDoneeType',
       'CompanyRegistrationNumber', 'Postcode', 'DonationType',
       'NatureOfDonation', 'PurposeOfVisit', 'DonationAction', 'ReceivedDate',
       'ReportedDate', 'IsReportedPrePoll', 'ReportingPeriodName', 'IsBequest',
       'IsAggregation', 'RegulatedEntityId', 'AccountingUnitId', 'DonorId',
       'CampaigningName', 'RegisterName', 'IsIrishSource', 'value', 'year',
       'Month'],
      dtype='object')

In [79]:
df.shape

(300, 31)

Let's get rid of the columns 'ECRef', 'AccountingUnitName', 'AccountingUnitsAsCentralParty', 'IsSponsorship', 'RegulatedDoneeType', 'CompanyRegistrationNumber', 'Postcode', 'DonationType','NatureOfDonation', 'PurposeOfVisit', 'DonationAction', 'ReceivedDate', 'ReportedDate', 'IsReportedPrePoll', 'ReportingPeriodName', 'IsBequest', 'IsAggregation', 'RegulatedEntityId', 'AccountingUnitId', 'RegisterName', 'IsIrishSource', 'AcceptedDateClean'. 

Let's drop some columns! `df = df.drop('Value', 1)`

.  
.  
.  
.  
.  
.  
.  
.  
.  
.  

Or, maybe we should just tell the computer what columns we like to keep. Might be shorter. :) 
Use `dfMini = df[['RegulatedEntityName', 'AcceptedDate', 'DonorName', 'DonorStatus', 'Year', 'Month','Value', 'RegulatedEntityType', 'DonorId', 'CampaigningName']]`

In [94]:
dfMini = df[['RegulatedEntityName', 'AcceptedDate', 'DonorName', 'DonorStatus', 'Year', 'Month','Value', 'RegulatedEntityType', 'DonorId', 'CampaigningName']]

KeyError: "['Year', 'Value'] not in index"

In [91]:
dfMini.sample(15)

NameError: name 'dfMini' is not defined

## Save your data

Now that we've put all this work into cleaning our dataset, let's save a copy. Off course Pandas has a nifty command for that too. Use `dfMini.to_csv('filename.csv', encoding='utf8')`. 

Be ware: use a different name than the filename of the original data file, or it will be overwritten.

In [95]:
dfMini.to_csv('results_clean.csv', encoding='utf8')

NameError: name 'dfMini' is not defined

In case you want to check if a new file was created in your directory, you can use the `pwd` and `ls` commands. At the beginning of this module, we used these commands to print the working directory (`pwd`) and list the content of the working directory (`ls`). 

First, use `pwd` to see in which folder - also known as directory - you are:

In [96]:
pwd

'C:\\Users\\nsommer\\Downloads'

Now use `ls` to get a list of all files in this directory. If everything worked your newly saved datafile should be among the files in the list.

In [97]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 42B7-F972

 Directory of C:\Users\nsommer\Downloads

03/15/2021  11:01 PM    <DIR>          .
03/15/2021  11:01 PM    <DIR>          ..
03/15/2021  10:02 PM    <DIR>          .ipynb_checkpoints
07/14/2020  04:27 PM         1,331,337 07D4B19D-516B-425D-9CDA-306403426618.jpeg
08/31/2020  11:10 AM            27,074 10040_DbyD_F20MW (1) (1).docx
09/08/2020  09:33 PM            27,074 10040_DbyD_F20MW (1) (2).docx
08/28/2020  11:09 AM            27,074 10040_DbyD_F20MW (1).docx
09/10/2020  06:33 PM         2,427,418 1538(Willa Palmer)_6145801373_In_00040007-BDB7-5F24-A019-00155D414209 (1) (1).wav
09/10/2020  05:21 PM         2,427,418 1538(Willa Palmer)_6145801373_In_00040007-BDB7-5F24-A019-00155D414209 (1).wav
11/04/2020  06:24 PM         1,009,818 1843(Nick Sommer)_2023619372_Out_000A0003-CCDA-5F07-57B3-00155D4D2F05.wav
09/09/2020  06:43 PM         1,266,138 1843(Nick Sommer)_2066505953_Out_000A0003-D27E-5F07-57B2-00155D4D2F05 (1).wav
09/09/2020  05:44 PM         1,266,138 1843(Nick Sommer)_2066505953_Out_000A0003-D27E-5F07-57B2-00155D4D2F05.wav
01/07/2021  06:11 PM           733,978 1843(Nick Sommer)_7149751255_Out_000A0000-E7E9-5F07-57B6-00155D4D2F05.wav
06/04/2020  04:14 PM           726,298 1843(Nick Sommer)_7402199075_Out_000D0001-209A-5C89-E234-000C29680CF7.wav
06/02/2020  06:55 PM         1,482,778 1843(Nick Sommer)_9136510541_Out_000B0001-10E8-5C89-E385-000C29049A9D.wav
06/04/2020  08:55 PM         1,370,298 1843(Nick Sommer)_9195422957_Out_000B0001-5465-5C89-E385-000C29049A9D.wav
07/14/2020  04:28 PM         5,116,676 18E2639F-0E4D-46F0-931F-C62670A117EF.jpeg
03/15/2021  11:01 PM           180,543 2 Clean data.ipynb
11/12/2020  10:23 AM           663,413 2016election.pdf
09/15/2020  07:11 PM         3,792,071 2B090FDD-FFC1-40FB-9A4B-856B864A5829.jpeg
05/27/2020  01:04 PM           283,178 3 Corporate Ext List.pdf
07/14/2020  03:55 PM           133,422 35.jpg
09/14/2020  12:54 PM         5,103,032 4807744B-7AED-4804-82C2-5964A83BCFAD.jpeg
09/15/2020  07:10 PM         3,467,903 4AB7296F-0566-4E32-B397-F75CFCBF8E83.jpeg
07/14/2020  05:41 PM         3,161,921 544A90D4-53DC-4D44-A36F-10F22C9D3FFB.jpeg
02/18/2021  12:58 PM         1,160,047 56B949B0-A160-45E9-9680-63408E131E8C.jpeg
09/01/2020  11:02 AM         3,392,033 66BC4B58-FBCE-40C9-B39F-CBE65083233E.jpeg
08/31/2020  07:03 PM         4,186,163 7950263B-424A-4EB0-A37C-54AE14CD6134.jpeg
07/08/2020  02:20 PM           157,889 94.pdf
07/14/2020  04:28 PM         3,147,794 9BA95113-5F8E-4D0A-A5EF-15F6ECE88D39.jpeg
09/15/2020  07:12 PM         3,332,702 9E262523-305C-4EF3-B90F-44D9D954D13C.jpeg
07/22/2020  01:44 PM            44,205 a_attack_graffiti.zip
09/01/2020  11:01 AM         3,562,318 AB034AF8-91B4-4DF6-AAA0-21820C57AE87.jpeg
09/15/2020  07:11 PM         3,577,934 AF27457C-69B0-4DA5-AFC2-6BA2CB1BFD83.jpeg
09/15/2020  07:11 PM         3,550,637 AF512A8C-3546-4913-8FAB-F880D899F1D0.jpeg
07/08/2020  02:03 PM           525,997 Afterwhite.pdf
09/08/2020  08:10 AM            10,725 Age of Presidents at Inauguration(1).xlsx
02/24/2021  10:10 PM       479,396,152 Anaconda3-2020.11-Windows-x86_64.exe
07/22/2020  02:49 PM           106,154 bad_signal.zip
02/14/2021  06:24 PM            17,345 Black Squirrel Radio Hour(1) (1).docx
02/14/2021  06:31 PM            17,345 Black Squirrel Radio Hour(1) (2).docx
02/02/2021  02:42 PM            17,345 Black Squirrel Radio Hour(1).docx
07/14/2020  04:27 PM         1,101,219 C12ED086-BDEF-4323-89E8-0724E8B7C9EB.jpeg
08/31/2020  07:04 PM         4,303,745 C6652E5A-245D-4F5E-B988-CB86F8ED8126.jpeg
11/03/2020  03:23 PM           150,016 Chapter_10 (1).doc
11/03/2020  02:47 PM           150,016 Chapter_10.doc
08/02/2020  12:29 PM            14,899 coverletter.docx
09/02/2020  02:37 PM         4,651,446 COVID (1).pptx
09/02/2020  02:37 PM         4,651,446 COVID.pptx
07/14/2020  04:28 PM         3,011,087 D4E8FC86-DA90-444F-8966-433B2B539A92.jpeg
07/14/2020  03:55 PM         3,525,050 D6719121-EB53-4A63-8752-FCDD21CAA991.jpeg
09/15/2020  07:11 PM         3,704,871 D8C6FF7E-88F9-4135-ABE9-B7C801F02697.jpeg
09/20/2020  10:16 PM             3,097 data-9_20_2020-10_16 PM.xlsx
07/14/2020  04:04 PM           441,749 deerjpg.jpg
02/11/2021  01:29 PM           237,771 Depression Syllabus FINAL(4) (1).docx
02/09/2021  01:28 PM           237,771 Depression Syllabus FINAL(4).docx
03/04/2021  08:42 PM           239,060 Depression Syllabus REVISED FEB 19 (1).docx
03/04/2021  08:43 PM           239,060 Depression Syllabus REVISED FEB 19 (2).docx
03/04/2021  08:41 PM           239,060 Depression Syllabus REVISED FEB 19.docx
03/03/2021  04:16 PM               771 Documents - Shortcut.lnk
07/14/2020  04:29 PM         4,643,878 E552E715-C525-4065-A394-8050CC2551A3.jpeg
07/14/2020  04:29 PM           748,634 E6557FCD-CEBC-40C7-BB37-3C62D89D588B.jpeg
09/01/2020  11:02 AM         3,256,910 E6D18A7D-7BDC-464C-A112-84DD17ABB2D3.jpeg
07/08/2020  08:24 PM           463,418 E7808ITOY.wav
07/08/2020  08:29 PM            68,378 E7808OTV2.wav
07/08/2020  08:26 PM           209,018 E7808OTZM (1).wav
07/08/2020  08:28 PM           209,018 E7808OTZM (2).wav
07/08/2020  08:29 PM           209,018 E7808OTZM (3).wav
07/08/2020  08:26 PM           209,018 E7808OTZM.wav
07/08/2020  08:16 PM            99,578 E78095T6Q.wav
07/08/2020  08:03 PM           309,818 E781A4UAA.wav
07/08/2020  08:15 PM           112,378 E781BLUDU (1).wav
07/08/2020  08:15 PM           112,378 E781BLUDU (2).wav
07/08/2020  08:06 PM           112,378 E781BLUDU.wav
07/08/2020  08:03 PM            70,778 E781CRUVM (1).wav
07/08/2020  08:02 PM            70,778 E781CRUVM.wav
07/08/2020  07:59 PM           363,258 E781D4U9U.wav
07/08/2020  08:01 PM           440,218 E781DJU2Q.wav
07/08/2020  07:11 PM           104,218 E781NPVKI (1).wav
07/08/2020  07:09 PM           104,218 E781NPVKI.wav
07/08/2020  07:09 PM           201,658 E781RGVYQ (1).wav
07/08/2020  07:02 PM           201,658 E781RGVYQ.wav
07/08/2020  07:01 PM           229,818 E781RLV2A (1).wav
07/08/2020  06:54 PM           229,818 E781RLV2A.wav
07/08/2020  06:51 PM            78,138 E781SQWCY.wav
07/08/2020  06:50 PM           271,578 E781TJWJ2.wav
07/08/2020  06:47 PM           229,338 E781U3WQ6 (1).wav
07/08/2020  06:46 PM           229,338 E781U3WQ6.wav
07/08/2020  06:48 PM           123,738 E781VBW1U.wav
07/08/2020  06:45 PM           149,178 E781WHW8Y.wav
07/08/2020  06:32 PM           184,378 E781XLXJM.wav
07/08/2020  06:45 PM           153,338 E781XMXM6 (1).wav
07/08/2020  06:34 PM           153,338 E781XMXM6.wav
07/08/2020  06:30 PM           110,778 E782B8YFM (1).wav
07/08/2020  06:30 PM           110,778 E782B8YFM (2).wav
07/08/2020  06:28 PM           110,778 E782B8YFM.wav
07/08/2020  06:32 PM           151,098 E782BOX4Y (1).wav
07/08/2020  06:30 PM           151,098 E782BOX4Y.wav
07/08/2020  06:22 PM           126,778 E782C0YTU (1).wav
07/08/2020  06:25 PM           126,778 E782C0YTU (2).wav
07/08/2020  06:19 PM           126,778 E782C0YTU.wav
07/08/2020  07:11 PM           248,058 E782C8Y4I.wav
07/08/2020  06:27 PM           131,578 E782CKYMQ.wav
07/08/2020  07:57 PM            70,138 E782F1ZMA (1).wav
07/08/2020  07:56 PM            70,138 E782F1ZMA.wav
07/08/2020  07:55 PM           113,658 E782F2ZPU (1).wav
07/08/2020  07:49 PM           113,658 E782F2ZPU.wav
07/08/2020  07:47 PM           103,098 E782F8Z0I.wav
07/08/2020  07:57 PM            72,058 E782FYZE6.wav
07/08/2020  07:55 PM           112,058 E782FZZIQ.wav
07/08/2020  07:46 PM            73,818 E782GLZ7M.wav
07/08/2020  08:55 PM           276,058 E787BNAR2.wav
07/08/2020  08:39 PM           263,738 E787CAAVM.wav
07/08/2020  08:55 PM           133,658 E787CKAY6 (1).wav
07/08/2020  08:46 PM           133,658 E787CKAY6.wav
07/08/2020  08:44 PM           179,578 E787CPA2Q.wav
07/08/2020  08:38 PM           194,618 E787E1BGY.wav
07/09/2020  08:28 PM           518,138 E8BKMHOUQ.wav
07/09/2020  08:27 PM           138,618 E8BKVHO8Y.wav
07/09/2020  08:22 PM           116,858 E8BKYWP4Y (1).wav
07/09/2020  08:20 PM           116,858 E8BKYWP4Y.wav
07/09/2020  07:58 PM           205,018 E8BMEZTLE.wav
07/09/2020  07:42 PM           279,418 E8BN1TWCY (1).wav
07/09/2020  07:37 PM           279,418 E8BN1TWCY.wav
07/09/2020  07:36 PM           452,378 E8BN3TWJ2.wav
07/09/2020  07:46 PM           352,058 E8BNLLVKI.wav
07/09/2020  07:42 PM           105,818 E8BNV6V5U.wav
07/09/2020  07:25 PM           215,738 E8BO60W8Y.wav
07/09/2020  07:24 PM           211,898 E8BO61XCI.wav
07/09/2020  07:34 PM            96,058 E8BO6IW1U.wav
07/09/2020  07:30 PM           136,218 E8BO6NW5E.wav
07/09/2020  07:17 PM           185,818 E8BO7TXF2.wav
07/09/2020  07:35 PM            56,698 E8BOX3WQ6.wav
07/09/2020  07:12 PM           111,738 E8BPAYXJM.wav
07/09/2020  07:11 PM            92,218 E8BPKTXQQ.wav
07/09/2020  07:09 PM           164,218 E8BPKUXUA.wav
07/09/2020  07:09 PM           127,098 E8BRW0YFM (1).wav
07/09/2020  07:09 PM           127,098 E8BRW0YFM.wav
07/09/2020  07:06 PM            96,698 E8BRYAYQA.wav
07/09/2020  06:59 PM           132,058 E8BRYBYTU.wav
07/09/2020  06:50 PM           135,578 E8BRYFYXE.wav
07/09/2020  06:49 PM           135,258 E8BRZWY4I.wav
07/09/2020  06:02 PM           313,498 E8BS0F1V2.wav
07/09/2020  06:01 PM            88,218 E8BS1K16Q.wav
07/09/2020  06:24 PM           188,698 E8BSCQ0IA (1).wav
07/09/2020  06:19 PM           188,698 E8BSCQ0IA.wav
07/09/2020  06:18 PM           150,618 E8BSFT0LU.wav
07/09/2020  06:09 PM           260,538 E8BSIF0PE.wav
07/09/2020  06:08 PM            65,498 E8BSO60Z2.wav
07/09/2020  06:08 PM           236,698 E8BSYM1EA (1).wav
07/09/2020  06:03 PM           236,698 E8BSYM1EA.wav
07/09/2020  05:43 PM           311,098 E8BT1735U.wav
07/09/2020  05:49 PM           155,098 E8BT1T3YQ.wav
07/09/2020  05:46 PM           261,978 E8BT1Y32A.wav
07/09/2020  05:43 PM           180,698 E8BT654CY (1).wav
07/09/2020  05:41 PM           180,698 E8BT654CY.wav
07/09/2020  05:41 PM            65,658 E8BT884NM.wav
07/09/2020  05:56 PM           208,058 E8BTOG3N2.wav
07/09/2020  05:56 PM            96,858 E8BTU43RM (1).wav
07/09/2020  05:52 PM            96,858 E8BTU43RM.wav
07/09/2020  05:52 PM           402,138 E8BTU83U6 (1).wav
07/09/2020  05:50 PM           402,138 E8BTU83U6.wav
07/09/2020  05:37 PM            41,018 E8BUA74UQ.wav
07/09/2020  05:35 PM           267,418 E8BUA84YA.wav
07/09/2020  05:34 PM           233,498 E8BUCV48Y.wav
07/14/2020  04:29 PM         1,022,532 E926A1F5-15D1-494B-B77E-1D13E9A61667.jpeg
03/09/2021  11:45 PM        36,578,420 EdDuko 44100 1_merged.wav
10/08/2020  03:55 PM            17,116 Election Report #1 Template (1).docx
10/08/2020  03:44 PM            17,116 Election Report #1 Template.docx
02/26/2021  10:45 PM               120 episode3 (1) (1).m3u
02/26/2021  10:41 PM               120 episode3 (1).m3u
02/26/2021  10:46 PM               120 episode3 (2).m3u
02/26/2021  10:40 PM               120 episode3.m3u
02/26/2021  09:59 PM       232,797,172 Episode3.mp4
02/11/2021  12:14 PM            16,075 EthicsModelsHandout.docx
02/11/2021  12:14 PM            14,117 EthicsModelsPhotojournalism (1).docx
02/11/2021  12:13 PM            14,117 EthicsModelsPhotojournalism.docx
07/14/2020  04:27 PM         1,331,379 F1549665-3EE7-4F48-93AD-CA239531D761.jpeg
09/15/2020  07:12 PM         3,588,313 F89C03AD-75C8-48B8-970A-ED8F8B2EA7A4.jpeg
01/25/2021  03:10 PM            37,976 FeatureWritingSyllabusSpring2021 (1).docx
02/16/2021  08:05 PM            37,976 FeatureWritingSyllabusSpring2021 (10).docx
02/17/2021  03:06 PM            37,976 FeatureWritingSyllabusSpring2021 (11).docx
02/17/2021  03:08 PM            37,976 FeatureWritingSyllabusSpring2021 (12).docx
02/22/2021  03:15 PM            37,976 FeatureWritingSyllabusSpring2021 (13).docx
02/24/2021  03:27 PM            37,976 FeatureWritingSyllabusSpring2021 (14).docx
03/03/2021  12:41 PM            37,976 FeatureWritingSyllabusSpring2021 (15).docx
03/03/2021  03:31 PM            37,976 FeatureWritingSyllabusSpring2021 (16).docx
03/08/2021  03:11 PM            37,976 FeatureWritingSyllabusSpring2021 (17).docx
03/10/2021  03:13 PM            37,976 FeatureWritingSyllabusSpring2021 (18).docx
03/15/2021  01:37 PM            37,976 FeatureWritingSyllabusSpring2021 (19).docx
01/25/2021  03:12 PM            37,976 FeatureWritingSyllabusSpring2021 (2).docx
03/15/2021  02:15 PM            37,976 FeatureWritingSyllabusSpring2021 (20).docx
03/15/2021  02:19 PM            37,976 FeatureWritingSyllabusSpring2021 (21).docx
01/27/2021  03:19 PM            37,976 FeatureWritingSyllabusSpring2021 (3).docx
01/29/2021  04:13 PM            37,976 FeatureWritingSyllabusSpring2021 (4).docx
02/01/2021  03:15 PM            37,976 FeatureWritingSyllabusSpring2021 (5).docx
02/03/2021  03:17 PM            37,976 FeatureWritingSyllabusSpring2021 (6).docx
02/08/2021  03:23 PM            37,976 FeatureWritingSyllabusSpring2021 (7).docx
02/08/2021  03:23 PM            37,976 FeatureWritingSyllabusSpring2021 (8).docx
02/10/2021  03:12 PM            37,976 FeatureWritingSyllabusSpring2021 (9).docx
01/20/2021  03:15 PM            37,976 FeatureWritingSyllabusSpring2021.docx
02/17/2021  07:24 PM               761 Final Project Areas - Interviewing & Data, Spring 21 - TOPIC AREAS.csv
02/17/2021  07:24 PM            17,272 Final Project Areas - Interviewing & Data, Spring 21.ods
02/17/2021  07:24 PM            10,073 Final Project Areas - Interviewing & Data, Spring 21.xlsx
02/10/2021  09:27 PM            13,428 Gamestop Stock Data.xlsx
09/08/2020  09:34 PM           817,799 ges3e_ppts_0101.pptx
09/14/2020  11:59 AM           772,000 ges3e_ppts_0104.pptx
12/09/2020  12:36 PM           888,599 ges3e_ppts_0801.pptx
07/22/2020  02:47 PM            24,426 graffitasi.zip
02/25/2021  11:03 AM             4,812 Hello Python! - IN CLASS (1).ipynb
02/25/2021  11:12 AM             4,812 Hello Python! - IN CLASS (2).ipynb
02/25/2021  11:03 AM             4,812 Hello Python! - IN CLASS.ipynb
01/25/2021  10:26 PM           806,855 IMG_0485.JPG
07/14/2020  04:30 PM           111,817 IMG_1162.JPG
07/14/2020  04:30 PM           137,025 IMG_1163.JPG
07/14/2020  04:30 PM            91,196 IMG_1164.JPG
07/14/2020  04:31 PM           128,476 IMG_1165.JPG
07/14/2020  04:31 PM           168,208 IMG_1167.JPG
07/14/2020  04:31 PM           197,989 IMG_1187.JPG
07/14/2020  04:32 PM           192,718 IMG_1188.JPG
07/14/2020  04:32 PM         1,111,073 IMG_1320.JPG
07/14/2020  04:32 PM           603,696 IMG_1321.JPG
07/14/2020  04:33 PM           601,941 IMG_1322.JPG
07/14/2020  04:33 PM           490,874 IMG_1323.JPG
09/16/2020  09:53 PM         2,589,328 IMG_2110.jpg
09/16/2020  09:53 PM         2,791,356 IMG_2111.jpg
09/16/2020  09:54 PM         2,484,037 IMG_2112.jpg
09/16/2020  09:54 PM         2,560,257 IMG_2113.jpg
09/16/2020  09:54 PM         2,443,956 IMG_2114.jpg
09/16/2020  09:54 PM         2,481,906 IMG_2115.jpg
09/16/2020  09:55 PM         2,611,214 IMG_2116.jpg
09/16/2020  09:55 PM         2,541,346 IMG_2117.jpg
09/18/2020  01:32 PM         2,900,537 IMG_2125.jpg
09/21/2020  12:43 PM         3,377,472 IMG_2140.jpg
09/21/2020  12:44 PM         2,951,251 IMG_2141 (1).jpg
09/21/2020  12:44 PM         2,951,251 IMG_2141.jpg
09/21/2020  12:45 PM         2,910,656 IMG_2142.jpg
09/21/2020  12:45 PM         3,721,533 IMG_2143.jpg
09/21/2020  12:45 PM         3,291,428 IMG_2144.jpg
09/23/2020  08:54 PM         2,772,707 IMG_2147.jpg
09/23/2020  08:55 PM         2,698,764 IMG_2148.jpg
09/23/2020  08:55 PM         2,557,550 IMG_2149.jpg
09/23/2020  08:55 PM         2,471,750 IMG_2150.jpg
09/23/2020  08:55 PM         2,412,457 IMG_2151.jpg
09/23/2020  08:55 PM         2,567,448 IMG_2152.jpg
09/23/2020  08:56 PM         2,299,556 IMG_2153.jpg
09/23/2020  08:56 PM         2,511,266 IMG_2154.jpg
09/23/2020  09:24 PM            96,283 IMG_2155.jpg
09/23/2020  09:23 PM         3,024,035 IMG_2156.jpg
09/23/2020  09:23 PM         2,674,274 IMG_2157.jpg
09/23/2020  09:23 PM         2,683,012 IMG_2158.jpg
09/23/2020  09:24 PM         2,625,545 IMG_2159.jpg
09/23/2020  09:24 PM         2,570,369 IMG_2160.jpg
09/23/2020  09:25 PM         2,770,618 IMG_2161.jpg
09/23/2020  09:25 PM         2,951,639 IMG_2162.jpg
09/25/2020  09:53 PM         2,999,867 IMG_2168.jpg
09/25/2020  09:53 PM         2,819,496 IMG_2169.jpg
09/25/2020  09:53 PM         2,713,697 IMG_2170.jpg
09/25/2020  09:54 PM         2,907,449 IMG_2171.jpg
09/29/2020  11:42 AM         3,826,401 IMG_2180.jpg
09/29/2020  11:42 AM         3,403,952 IMG_2181.jpg
09/29/2020  11:42 AM         3,544,267 IMG_2182.jpg
09/29/2020  11:43 AM         3,721,058 IMG_2183.jpg
09/29/2020  11:43 AM         3,864,044 IMG_2184.jpg
10/01/2020  01:04 PM         3,152,331 IMG_2193.jpg
10/01/2020  01:04 PM         3,595,885 IMG_2194.jpg
10/02/2020  01:33 PM         3,210,808 IMG_2197.jpg
10/02/2020  01:34 PM         3,038,350 IMG_2198.jpg
10/02/2020  11:06 PM         3,074,006 IMG_2200.jpg
10/02/2020  11:06 PM         2,730,586 IMG_2201.jpg
10/02/2020  11:07 PM         2,478,186 IMG_2202.jpg
10/05/2020  10:37 PM         2,455,386 IMG_2256.jpg
10/05/2020  10:38 PM         2,567,680 IMG_2257.jpg
10/05/2020  10:38 PM         2,651,240 IMG_2258.jpg
10/05/2020  10:38 PM         2,618,863 IMG_2259.jpg
10/07/2020  09:27 PM         2,819,306 IMG_2266.jpg
10/07/2020  09:27 PM         2,631,394 IMG_2267.jpg
10/07/2020  09:28 PM         2,631,394 IMG_2268.jpg
10/12/2020  10:13 AM         2,524,954 IMG_2274.jpg
10/12/2020  10:13 AM         2,627,908 IMG_2275.jpg
10/12/2020  10:13 AM         2,562,079 IMG_2276.jpg
10/12/2020  10:13 AM         2,612,194 IMG_2277.jpg
10/13/2020  02:30 PM         3,508,759 IMG_2283.jpg
10/14/2020  09:14 PM         2,544,329 IMG_2288.jpg
10/14/2020  09:14 PM         2,568,378 IMG_2289.jpg
10/17/2020  03:18 PM         3,034,048 IMG_2307.jpg
10/22/2020  11:02 AM         3,080,825 IMG_2348.jpg
10/22/2020  11:02 AM         3,389,623 IMG_2349.jpg
10/22/2020  11:02 AM         3,386,029 IMG_2350.jpg
10/25/2020  12:38 PM         3,293,754 IMG_2361.jpg
10/25/2020  12:38 PM         2,541,897 IMG_2362.jpg
10/25/2020  12:38 PM         3,261,297 IMG_2363.jpg
10/27/2020  04:39 PM         2,722,184 IMG_2365.jpg
10/27/2020  04:40 PM         2,726,015 IMG_2366.jpg
10/27/2020  04:40 PM         2,604,864 IMG_2367.jpg
10/28/2020  09:06 PM         2,709,060 IMG_2372.jpg
10/31/2020  03:48 PM           108,735 IMG_2383.jpg
10/31/2020  03:49 PM         3,233,637 IMG_2384.jpg
10/31/2020  03:49 PM         3,369,164 IMG_2385.jpg
10/31/2020  03:48 PM         3,267,651 IMG_2386.jpg
10/31/2020  03:48 PM         3,242,320 IMG_2387.jpg
10/31/2020  03:48 PM         3,310,827 IMG_2388.jpg
10/31/2020  03:49 PM         3,461,474 IMG_2389.jpg
10/31/2020  03:49 PM         3,047,631 IMG_2390.jpg
11/08/2020  07:57 PM         2,692,322 IMG_2419 (1).jpg
11/08/2020  07:57 PM         2,692,322 IMG_2419.jpg
11/08/2020  07:58 PM         2,628,680 IMG_2420.jpg
11/08/2020  07:58 PM         2,797,981 IMG_2421.jpg
11/09/2020  11:05 PM         2,414,954 IMG_2426.jpg
11/09/2020  11:05 PM         2,309,504 IMG_2427.jpg
11/09/2020  11:05 PM         2,299,760 IMG_2428.jpg
11/09/2020  11:05 PM         2,505,083 IMG_2429.jpg
11/09/2020  11:06 PM         2,492,155 IMG_2430.jpg
11/17/2020  01:48 PM         2,857,610 IMG_2461.jpg
11/17/2020  01:48 PM         2,789,617 IMG_2462.jpg
11/17/2020  01:49 PM         3,026,043 IMG_2463.jpg
11/17/2020  01:49 PM         2,676,391 IMG_2464.jpg
11/30/2020  10:45 PM         2,620,448 IMG_2522.jpg
11/30/2020  10:45 PM         2,559,804 IMG_2523.jpg
12/04/2020  01:02 PM         3,126,785 IMG_2537.jpg
12/07/2020  04:34 PM         1,914,165 IMG_2551.jpg
12/07/2020  11:42 PM         2,711,723 IMG_2552.jpg
12/15/2020  03:36 PM         3,150,596 IMG_2560.jpg
12/15/2020  03:36 PM         3,412,529 IMG_2561.jpg
12/15/2020  03:36 PM         3,131,308 IMG_2562.jpg
12/16/2020  12:52 PM         2,348,854 IMG_2572.jpg